export const AUTO_COMPLETE_SUGGESTIONS = [
  "Hello!",
  "How are you?",
  "What's up?",
  "Thank you!",
  "You're welcome.",
  "Please.",
  "Sorry.",
  "No problem.",
  "Goodbye!",
  "See you later.",
  "Take care.",
  "Have a great day!",
  "Yes.",
  "No.",
  "Maybe.",
  "I don't know.",
  "Can you help me?",
  "Sure!",
  "Absolutely.",
  "Let's do it!",
];

export const SELECT_OPTIONS = [
  "Select option 1",
  "Select option 2",
  "Select option 3",
  "Select option 4",
  "Select option 5",
];
